Qa python homework 1
ikramanop/2020-1-Atom-QA-Python-L-Marder pull request #1
Opened 2020-02-29 17:03 UTC by ikramanop

# Домашнее задание № 1

Прошу @snicks92 или @z1ll1 проверить его.

Что было сделано:
* Написаны тесты по структурам List, Set, Dictionary, String, Int;
* Тесты содержатся в классах, по каждой структуре есть набор параметризованных тестов;
* Проверяются сами структуры, так и их методы, а также функции, напрямую с ними связанные;
* Все тесты проверены линтером pylint, а также на соответствие стандарту PEP8;
* Настроено тестовое окружение и сгенерирован файлик requirements.txt.

2020-03-01 11:18 UTC, sniiick requested changes

2020-03-01 11:18 UTC, snicks92 commented on hw1/test_1.py
> +    def test_list_1_3(self, i):
Если я верно понял идею, то тест test_list_1_2 добавляет 10 элементов в список, а test_list_1_3 удаляет эти же элементы. И все это на одном и том же self.buff_list. Идея хорошая, но тесты получаются зависимые. То есть если вдруг test_list_1_2 случайно упадет и не добавит 9, то и test_list_1_3 упадет на удалении 9. 

Именно поэтому тесты должны быть атомарными и в идеале каждый тест должен сам приготовить себе тестовые данные.

PS. + с точки зрения классов эквивалентности нет смысла добавлять весь рендж, что именно мы добавляем в список нее имеет значения, так что в целом от параметризации тут можно отказаться

2020-03-01 11:18 UTC, snicks92 commented on hw1/test_2.py
> +    def test_set_1_3(self, i):
Тут то же самое что и с интом. Надо сделать тесты атомарными. 
Кстати, хороший пример, если я попробую запустить только этот тест отдельно через `pytest -k test_set_1_3`, то понимаешь что произойдет =) Тест упадет так как сет пустой

2020-03-01 11:18 UTC, snicks92 commented on hw1/test_2.py
> +        self.buff_set = set(i for i in range(length))
можно просто `set(range(length))`

2020-03-01 11:18 UTC, snicks92 commented on hw1/test_2.py
> +        self.buff_set.update(set(i for i in range(length)))
Аналогично можно просто `set(range(length))`
Ну и все та же история, если предыдущий тест не очистит сет, то этот тест упадет.

2020-03-01 11:18 UTC, snicks92 commented on hw1/test_5.py
> +    @pytest.mark.parametrize('i', range(10))
Весь range тут довольно избыточно. Можно взять только пару тройку значений

2020-03-01 11:20 UTC, snicks92 commented
Оставил комментарии. В целом все хорошо, в кратце:
- тесты должны быть атомарными и не влиять на результат друг друга, возможно поэтому пользовать статическими аттрибутами классов для данного задания не очень подходит
- я бы переименовал файлы аналогично по названию структуры, которую они тестируют, например `test_int.py`
- в некоторых местах избыточная параметризация, я бы сократил количество эквивалентных проверок

2020-03-03 13:29 UTC, snicks92 commented on hw1/test_1.py
> +    def test_list_1_3(self, i):
Ладно, зависимости ты подкостылял и оно даже работает. Но в следующий раз я настоятельно НЕ рекомендую натравливать разные тесты на одни и те же изменяемые объекты.

2020-03-03 13:47 UTC, sniiick requested changes
Разберись почему падает test_set_2_2, поправь и зачту домашку.

2020-03-03 13:47 UTC, snicks92 commented on hw1/test_set.py
> +    def test_set_2_2(self, i):
Периодически падает. Знаю почему, но предлагаю тебе самому разобраться.
```
self = <test_set.TestSet2 object at 0x10c616a60>, i = 9

    @pytest.mark.parametrize('i', range(10))
    def test_set_2_2(self, i):
        """тест правильности метода copy"""
>       assert  self.buff_set.pop() == self.buff_setcopy.pop()
E       KeyError: 'pop from an empty set'

i          = 9
self       = <test_set.TestSet2 object at 0x10c616a60>

hw1/test_set.py:63: KeyError
```

2020-03-03 13:54 UTC, ikramanop commented on hw1/test_set.py
> +    def test_set_2_2(self, i):
Интересная ошибка получилась. Забыл одну из главных особенностей set.

2020-03-03 14:55 UTC, sniiick approved these changes

2020-03-03 14:55 UTC, merged